image: docker-proxy.device-insight.com/library/maven:alpine

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:stable-dind

mvn_test_job:
  stage: build
  script: >
    mvn clean install -B -P gitlab
  artifacts:
    paths:
      - kafka-health-check/target/*.log
    when: on_failure
    expire_in: 1 week
  except:
    - master
    - develop
  tags:
    - dind

mvn_deploy_job:
  stage: build
  script: >
    mvn clean deploy -B -P gitlab
  artifacts:
    paths:
      - kafka-health-check/target/*.log
    when: on_failure
    expire_in: 1 week
  only:
    - master
    - develop
  tags:
    - dind
